database:
  host: (hostname)
  port: (port)
  username: root
  password: (pwd)
  dbname: (dbname)

webtoken_sigkey: (64字符Base64 如YKFAq3akQp5pEEAU8UqnrMGUr9lg4DxZZj6uRkHdcugUAcnxF89HunEkUugD0kIP)

fileobjects:
  dir: D:/JHET_TESTONLY